### ISSUE TITLE
Booting on cloud VM

### ISSUE THREAD

**Issue by atanasmatev** [plajjan/vrnetlab#228] opened 2020-05-24 18:20 UTC
Hi,

 I tried both CSR and XVR images (from the list of supported firmwares). It stops just a few seconds after running the container and it stays like this forver. Port 22 is open on the container though but no "ssh" banner or anything.
[root@virtualserver01 ~]# docker logs e1820d46918b
2020-05-24 18:09:51,216: vrnetlab   DEBUG    Creating overlay disk image
2020-05-24 18:09:51,233: vrnetlab   DEBUG    Starting vrnetlab CSR
2020-05-24 18:09:51,234: vrnetlab   DEBUG    VMs: [<__main__.CSR_vm object at 0x7f736cd25588>]
2020-05-24 18:09:51,247: vrnetlab   DEBUG    VM not started; starting!
2020-05-24 18:09:51,247: vrnetlab   INFO     Starting CSR_vm
2020-05-24 18:09:51,248: vrnetlab   DEBUG    ['qemu-system-x86_64', '-display', 'none', '-machine', 'pc', '-monitor', 'tcp:0.0.0.0:4000,server,nowait', '-m', '4096', '-serial', 'telnet:0.0.0.0:5000,server,nowait', '-drive', 'if=ide,file=/csr1000v-universalk9.16.03.01a-overlay.qcow2', '-device', 'pci-bridge,chassis_nr=1,id=pci.1', '-device', 'e1000,netdev=p00,mac=52:54:00:2a:b3:00', '-netdev', 'user,id=p00,net=10.0.0.0/24,tftp=/tftpboot,hostfwd=tcp::2022-10.0.0.15:22,hostfwd=udp::2161-10.0.0.15:161,hostfwd=tcp::2830-10.0.0.15:830,hostfwd=tcp::2080-10.0.0.15:80,hostfwd=tcp::2443-10.0.0.15:443', '-device', 'e1000,netdev=p01,mac=52:54:00:5d:29:01,bus=pci.1,addr=0x2', '-netdev', 'socket,id=p01,listen=:10001', '-device', 'e1000,netdev=p02,mac=52:54:00:9f:d7:02,bus=pci.1,addr=0x3', '-netdev', 'socket,id=p02,listen=:10002', '-device', 'e1000,netdev=p03,mac=52:54:00:83:35:03,bus=pci.1,addr=0x4', '-netdev', 'socket,id=p03,listen=:10003', '-device', 'e1000,netdev=p04,mac=52:54:00:33:a4:04,bus=pci.1,addr=0x5', '-netdev', 'socket,id=p04,listen=:10004', '-device', 'e1000,netdev=p05,mac=52:54:00:f6:9c:05,bus=pci.1,addr=0x6', '-netdev', 'socket,id=p05,listen=:10005', '-device', 'e1000,netdev=p06,mac=52:54:00:71:52:06,bus=pci.1,addr=0x7', '-netdev', 'socket,id=p06,listen=:10006', '-device', 'e1000,netdev=p07,mac=52:54:00:32:59:07,bus=pci.1,addr=0x8', '-netdev', 'socket,id=p07,listen=:10007', '-device', 'e1000,netdev=p08,mac=52:54:00:35:9f:08,bus=pci.1,addr=0x9', '-netdev', 'socket,id=p08,listen=:10008', '-device', 'e1000,netdev=p09,mac=52:54:00:e2:e3:09,bus=pci.1,addr=0xa', '-netdev', 'socket,id=p09,listen=:10009']

I have Docker and the KVM driver loaded. This is Citrix environment and hardware based nested virtualization is not really supported but I can run containers with the native Linux driver. Have you seen this issue before? Could it be related to the fact that I am trying to run it on CentOS VM?

Thanks.

**Comment by atanasmatev** [comment] 2020-05-24 23:45
Let me elaborate a bit more. So it stays with the message above for about 10 minutes. During this time ports 22, 830 are open but there aren't any services listening on these ports (e.g. I can't ssh). After about 10 minutes it seems like the router starts running the last two lines from above in a loop every 10-20 seconds:
2020-05-24 18:09:51,247: vrnetlab INFO Starting CSR_vm
2020-05-24 18:09:51,248: vrnetlab DEBUG ['qemu-system-x86_64', .......... (5 pages long command line parameters)
--- in 10-20 seconds ---
2020-05-24 18:09:51,247: vrnetlab INFO Starting CSR_vm
2020-05-24 18:09:51,248: vrnetlab DEBUG ['qemu-system-x86_64',  ......

**Comment by robertsilar** [comment] 2020-12-08 14:54
I'm having a very similar issue with CSR in a VMware environment.   
Did you manage to resolve it or find out the cause?

**Comment by atanasmatev** [comment] 2020-12-08 18:21
My post was about running this in container. The solution was ... just to wait more. It took something line 20 minutes to get the container up. I tried it on my personal PC ... took even longer.

**Comment by plajjan** [comment] 2021-01-18 20:08
The qemu process doesn't have access to KVM hardware acceleration. This is evident of the qemu args, as there's not `-enable-kvm` argument in there. If the `/dev/kvm` device would have been available, it would have enabled KVM.

Lack of hardware acceleration means it is going to be very slow, which is congruent with the described symptoms. I am going to close this as it's not a bug or feature enhancement.

**Closed by plajjan** 2021-01-18 20:08 UTC
