### ISSUE TITLE
Support for Juniper's vQFX10000 in vrnetlab

### ISSUE THREAD

**Issue by afressancourt** [plajjan/vrnetlab#102] opened 2017-03-16 10:36 UTC
Hello,

Juniper has recently released its vQFX10000 virtual router instance for testing (See https://www.juniper.net/us/en/dm/free-vqfx-trial/). This virtual router instance works in a similar way as the vMX virtual router, with a Router engine (re) and a Path Forward engine (pfe).

The re and pfe virtual images can be downloaded from Juniper's website in a Vagrant box format or as a VMDK to be used with VMWare or ESXi. Yet, after converting the VMDK image into a QCOW2 file with:
 
`qemu-img convert -f vmdk vqfx10k-re-15.1X53-D60.vmdk -O qcow2 vqfx10k-re-15.1X53-D60.qcow2`

 I have been able to boot the re and the pfe using the following command line:
`qemu-system-x86_64 -enable-kvm -display curses -machine pc -m 1024 -serial telnet:0.0.0.0:5000,server,nowait -drive if=ide,file=./vqfx10k-re-15.1X53-D60.qcow2`

According to documentation and experiment reports for running vQFX10k, the re and pfe VM have the following requirements:
* RE
  * vCPU: 1
  * RAM: 1024 MB
* PFE
  * vCPU: 1
  * RAM: 2048 MB (even down to 1536 MB according to some reports)

For both appliances, using a e1000 virtual NIC is suitable. 

Unfortunately, I am not very familiar with vrnetlab's structure so contributing to a branch to add the virtual appliance is complex, yet, I am more than eager to learn !

Best regards,

Antoine

**Comment by plajjan** [comment] 2017-03-16 12:37
Dupe of #72.

I have seen that vQFX is released now and I actually downloaded an image but I have yet to get around to doing anything with it.

qemu reads vmdk files just fine - you don't need to convert them to qcow2 first.

**Comment by afressancourt** [comment] 2017-03-16 13:22
Sorry for duplicate issue

**Comment by plajjan** [comment] 2017-03-16 13:51
No problem :)

I began playing a bit with this:
```
2017-03-16 12:58:49,069: vrnetlab   INFO     STDERR: qemu-system-x86_64: -drive if=ide,file=/vqfx10k-re-15.1X53-D60.vmdk: could not open disk image /vqfx10k-re-15.1X53-D60.vmdk: VMDK version 3 must be read only
```
so maybe converting to qcow2 isn't such a bad idea after all.. or use an overlay.

**Comment by plajjan** [comment] 2017-03-16 14:09
Using an overlay seems to work...

**Comment by afressancourt** [comment] 2017-03-16 15:07
Indeed, it turns out the qcow2 file is larger than the vmdk.

**Comment by plajjan** [comment] 2017-03-16 15:21
Yeah? That's surprising.. at least if it's a big difference.

The image already contains credentials and stuff.. a little weird. Anyway, I got something up and running now although the interfaces aren't working just yet. It's merged to master already so you can have a look.

**Comment by plajjan** [comment] 2017-03-16 17:33
@afressancourt it seems to be working now. I have yet to check connectivity but it boots up and after quite a long time (10-15 minutes) xe- interfaces come up!

**Comment by plajjan** [comment] 2017-03-17 08:44
Now I have checked connectivity and it's working A-ok.

Here's a ping to a XR router and it works, yay! :D
```
root@vqfx-re# run ping 192.168.2.2
PING 192.168.2.2 (192.168.2.2): 56 data bytes
64 bytes from 192.168.2.2: icmp_seq=0 ttl=255 time=9.450 ms
64 bytes from 192.168.2.2: icmp_seq=1 ttl=255 time=8.816 ms
64 bytes from 192.168.2.2: icmp_seq=2 ttl=255 time=11.138 ms
```
Closing issue.

**Closed by plajjan** 2017-03-17 08:44 UTC

**Comment by afressancourt** [comment] 2017-03-17 08:48
Thanks a lot, I am trying that right now!

**Comment by afressancourt** [comment] 2017-03-17 10:58
I managed to get the first VM running after 10 min booting, the second takes a while loading on my laptop (30 minutes and counting). I will try to run on a slightly stronger platform to see how it turns out.

**Comment by plajjan** [comment] 2017-03-17 11:24
Aha, too slow CPU? I haven't actually tried to start two vQFX but I don't think there's any problem with that.

**Comment by Halwaran** [comment] 2017-10-25 09:07
Please, who can tell me where can i download vQFX images,because I can not download from juniper website.
Please help me I would like to learn.
My email. sap.system@hotmail.com

Thanks.

**Comment by plajjan** [comment] 2017-10-25 12:33
@Halwaran there's a link in the readme file to the juniper page where you can download the images. You need a Juniper account but anyone can create one for the purpose of obtaining an evaluation image.

**Comment by mudassar7777** [comment] 2018-06-23 00:41
@plajjan can you pl share vqfx images. i m unable to download from juniper
